import Head from 'next/head'
import ParticlesTest from '@/components/ParticlesTest'
import styles from '../../styles/Home.module.css'
import { useState } from 'react';
import audioSelect from '../../assets/menu-navigate-sound.mp3';
import audioNavigate from '../../assets/menu-select.mp3';
import useKeypress from 'react-use-keypress';
import LinkIcon from '@mui/icons-material/Link';
import GitHubIcon from '@mui/icons-material/GitHub';
import KeyboardBackspaceIcon from '@mui/icons-material/KeyboardBackspace';
import { Inter } from '@next/font/google'
import { Box } from '@mui/material';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Projects() {
  const router = useRouter();

  const [MenuItemSelected, setMenuItemSelected] = useState<number>(1);

  useKeypress(['ArrowUp', 'ArrowDown', 'Enter'], (event) => {
    switch (event.key) {
      case 'ArrowUp':
        audioPlay('navigate');
        setMenuItemSelected(prev => prev === 1 ? 3 : prev - 1);
        break;
      case 'ArrowDown':
        audioPlay('navigate');
        setMenuItemSelected(prev => prev === 3 ? 1 : prev + 1);
        break;
        // case 'Enter':
        //   handleItemSelect();
        break;
      default:
        break;
    }
  });

  const hoverHandler = (itemNumber: number) => {
    setMenuItemSelected(itemNumber);
    audioPlay('navigate');
  }

  const audioPlay = (sfxName: 'navigate' | 'select') => {
    switch (sfxName) {
      case 'navigate':
        new Audio(audioNavigate).play();
        break;
      case 'select':
        new Audio(audioSelect).play();
        break;
      default:
        break;
    }
  }


  return (
    <>
      <Head>
        <title>Vasilis Litsas - Project samples</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ParticlesTest />

      <main className={styles.main}>

        <div style={{ position: "absolute", top: 30, left: 30, cursor: "pointer" }} className="flex-center-y" onClick={() => router.back()}>
          <KeyboardBackspaceIcon />&nbsp;Back
        </div>

        <div className={styles.titles}>
          <h1>Project samples</h1>
          <br />
          <h5>Links to projects websites and code</h5>
        </div>

        <div className={styles.center}>
          <div
            onMouseEnter={() => hoverHandler(1)}
            className={`flex-center-y jcsb ${styles.menuitem} ${MenuItemSelected === 1 ? styles.selected : ''}`}>
            <h3 className={`text-center`}>The dashboard</h3>
            <Box className="flex-center-y">
              <a className={styles.link} target="_blank" href="https://statuesque-strudel-d3a015.netlify.app"><LinkIcon /></a>
              <a className={styles.link} target="_blank" href="https://github.com/vasilis-lts/the-dashboard"><GitHubIcon /></a>
            </Box>
          </div>
          <div
            onMouseEnter={() => hoverHandler(2)}
            className={`flex-center-y jcsb ${styles.menuitem} ${MenuItemSelected === 2 ? styles.selected : ''}`}>
            <h3 className={`text-center`}>Genetic algorithm</h3>
            <Box className="flex-center-y">
              <a className={styles.link} target="_blank" href="https://optimistic-noether-48efcb.netlify.app"><LinkIcon /></a>
              <a className={styles.link} target="_blank" href="https://github.com/vasilis-lts/Genetic-Algorithm-Performance"><GitHubIcon /></a>
            </Box>
          </div>
          <div
            onMouseEnter={() => hoverHandler(3)}
            className={`flex-center-y jcsb ${styles.menuitem} ${MenuItemSelected === 3 ? styles.selected : ''}`}>
            <h3 className={`text-center`}>Progressive web app</h3>
            <Box className="flex-center-y">
              <a className={styles.link} target="_blank" href="https://asset.softnet.com.gr/"><LinkIcon /></a>
              <a className={styles.link} target="_blank" href="https://github.com/vasilis-lts/react-jira"><GitHubIcon /></a>
            </Box>
          </div>
          <p style={{ marginTop: 20 }}>More to be uploaded soon...</p>
        </div>
      </main>

    </>
  )
}
